"""empty message

Revision ID: 7c755704fe3c
Revises: 5c4900e514dd
Create Date: 2018-02-06 09:46:35.636951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c755704fe3c'
down_revision = '5c4900e514dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review', sa.String(length=140), nullable=True))
    op.add_column('reviews', sa.Column('title', sa.String(length=40), nullable=True))
    op.drop_index('ix_reviews_timestamp', table_name='reviews')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'message')
    op.drop_column('reviews', 'answer')
    op.drop_column('reviews', 'user_id')
    op.drop_column('reviews', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.add_column('reviews', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('reviews', sa.Column('answer', sa.VARCHAR(length=140), nullable=True))
    op.add_column('reviews', sa.Column('message', sa.VARCHAR(length=140), nullable=True))
    op.create_foreign_key(None, 'reviews', 'user', ['user_id'], ['id'])
    op.create_index('ix_reviews_timestamp', 'reviews', ['timestamp'], unique=False)
    op.drop_column('reviews', 'title')
    op.drop_column('reviews', 'review')
    # ### end Alembic commands ###
